### PR TITLE
WPE Support

### PR DESCRIPTION
**Pull request by psivasubramanian**
Added required changes to make it work with WPE browser also.

### CODE REVIEW

**Review by andrey-konovalov — CHANGES_REQUESTED** [review]
This patch set must be reworked.
The general issues are:
1) a single change is split into a bunch of commits with the same name. E.g. one commit changes the function declaration, and the other one changes the function definition - in particular, this breaks the rule that any single commit shouldn't cause compilation errors (remember git bisect).
2) commits representing logically independent changes named exactly the same
3) commit names and the descriptions doesn't explain anything about the change

Commit "ClearKey: fix typo" is not needed: it fixes the typo introduced by another commit in this pull request. So instead of adding the extra commit, the commit which introduced this typo must be fixed.

I also have questions on the changes themselves. See my next comments.

**Comment by andrey-konovalov** [comment]
```
--- a/cdmi-stub/imp.h
+++ b/cdmi-stub/imp.h
@@ -88,8 +88,8 @@ class CMediaKeys : public IMediaKeys
     virtual ~CMediaKeys(void);
 
     virtual bool IsTypeSupported(
-        const char *f_pwszMimeType,
-        const char *f_pwszKeySystem) const;
+        const char *f_pwszKeySystem,
+        const char *f_pwszMimeType) const;
```
Why do you change the arguments order in CMediaKeys::IsTypeSupported() ?
If this is just to match the order in the call in cdmi/service.cpp, line 117, then maybe this is that call with wrong order of the args which needs to be fixed? (Also you changed CMediaKeys::IsTypeSupported() w/o changing IMediaKeys::IsTypeSupported() in the parent class)

**Comment by andrey-konovalov** [comment]
https://github.com/linaro-home/open-content-decryption-module-cdmi/pull/7/files#diff-b66288d20ff8b0bd3caab1ec031c24c4R161 : `#if WPE`
https://github.com/linaro-home/open-content-decryption-module-cdmi/pull/7/files#diff-b66288d20ff8b0bd3caab1ec031c24c4R179 : `#ifndef WPE`

My guess is that for WPE build `WPE` will be set to non-zero value. But existing builds don't set `WPE` and should not do that. For this reason and for consistency please use `#ifdef WPE` and `ifndef WPE` throughout the patchset (no `#if WPE`).

**Comment by andrey-konovalov** [comment]
```
#if WPE
       struct {
               u_int message_len;
               char *message_val;
       } message;
#else  //chrome	
	char *message;
#endif
```
- this change needs an explanation: why it must be the structure instead of e.g. zero-terminated string (which strlen() could be used on).

File: cdmi-stub/imp.h [hunk 1]
```diff
@@ -88,8 +88,8 @@ class CMediaKeys : public IMediaKeys
     virtual ~CMediaKeys(void);
 
     virtual bool IsTypeSupported(
-        const char *f_pwszMimeType,
-        const char *f_pwszKeySystem) const;
+        const char *f_pwszKeySystem,
+        const char *f_pwszMimeType) const;
```
Comment (petegriffin) [inline cdmi-stub/imp.h]: Why swap the order of the parameters?

**Comment by andrey-konovalov** [comment]
The `RPC_OPEN_CDM_MEDIAKEYS*` redefines!

Introducing new RPC_OPEN_CDM_MEDIAKEYSESSION_LOAD:
```
+#if WPE
+#define RPC_OPEN_CDM_MEDIAKEYSESSION_LOAD 5
+#else	// Chromium
 #define RPC_OPEN_CDM_MEDIAKEYS_LOAD_SESSION 4
+#endif	
```
- results only in extra `#if` which otherwise would not be needed:
```
+#if WPE
￼ +        case RPC_OPEN_CDM_MEDIAKEYSESSION_LOAD:
￼ +#else	// Chromium
￼  	case RPC_OPEN_CDM_MEDIAKEYS_LOAD_SESSION:
￼ +#endif	
```

And the whole:
```
#if WPE
#define RPC_OPEN_CDM_MEDIAKEYS_SET_SERVER_CERTIFICATE 3
#define RPC_OPEN_CDM_MEDIAKEYS_CREATE_SESSION 4
#define RPC_OPEN_CDM_MEDIAKEYSESSION_LOAD 5
#define RPC_OPEN_CDM_MEDIAKEYSESSION_UPDATE 6
#define RPC_OPEN_CDM_MEDIAKEYSESSION_REMOVE 7
#define RPC_OPEN_CDM_MEDIAKEYSESSION_CLOSE 8
#define RPC_OPEN_CDM_MEDIAKEYSESSION_RELEASE 9
#define RPC_OPEN_CDM_MEDIAENGINE 10
#else	//Chromium
#define RPC_OPEN_CDM_MEDIAKEYS_CREATE_SESSION 3
#define RPC_OPEN_CDM_MEDIAKEYS_LOAD_SESSION 4
#define RPC_OPEN_CDM_MEDIAKEYSESSION_UPDATE 5
#define RPC_OPEN_CDM_MEDIAKEYSESSION_RELEASE 6
#define RPC_OPEN_CDM_MEDIAENGINE 7
#endif	
```
couldn't it be replaced with just the change below (w/o "renumbering" the existing `#define`'s)?
Extending the protocol by changing the existing constants looks a very wrong way for me.
And we have full control on the matching part - open-content-decryption-module, src/com/common/rpc/opencdm_xdr.h - right?
```
# WPE specific defines
#define RPC_OPEN_CDM_WPE_MEDIAKEYS_SET_SERVER_CERTIFICATE 100
#define RPC_OPEN_CDM_WPE_MEDIAKEYSESSION_REMOVE 101
#define RPC_OPEN_CDM_WPE_MEDIAKEYSESSION_CLOSE 102
```

File: rpc/opencdm_xdr.h [hunk 2]
```diff
@@ -127,19 +130,39 @@ extern  rpc_response_generic * rpc_open_cdm_is_type_supported_1_svc(rpc_request_
 #define RPC_OPEN_CDM_MEDIAKEYS 2
 extern  rpc_response_generic * rpc_open_cdm_mediakeys_1(rpc_request_mediakeys *, CLIENT *);
 extern  rpc_response_generic * rpc_open_cdm_mediakeys_1_svc(rpc_request_mediakeys *, struct svc_req *);
+#if WPE
+#define RPC_OPEN_CDM_MEDIAKEYS_SET_SERVER_CERTIFICATE 3
+#define RPC_OPEN_CDM_MEDIAKEYS_CREATE_SESSION 4
+#else	//Chromium
```
Comment (petegriffin) [inline rpc/opencdm_xdr.h]: The changes you are making to RPC layer and all the #ifdef WPE mean we can't have a common CDMi which works for both Chromium and WPE browsers at the same time.

One reason for the OpenCDM architecture and having "browser glue" in the OpenCDM plugin is to abstract away the browser differences so the other parts can be browser agnostic. By putting #ifdef BROWSER in this layer we are breaking this abstraction, and moving browser specific code into the CDMi.

File: rpc/opencdm_xdr_svc.c [hunk 3]
```diff
@@ -54,8 +54,11 @@ open_cdm_1(struct svc_req *rqstp, register SVCXPRT *transp)
 		_xdr_result = (xdrproc_t) xdr_rpc_response_create_session;
 		local = (char *(*)(char *, struct svc_req *)) rpc_open_cdm_mediakeys_create_session_1_svc;
 		break;
-
+#if WPE
+        case RPC_OPEN_CDM_MEDIAKEYSESSION_LOAD:
+#else	// Chromium
 	case RPC_OPEN_CDM_MEDIAKEYS_LOAD_SESSION:
```
Comment (petegriffin) [inline rpc/opencdm_xdr_svc.c]: Why can't they be the same?

File: cdmi-stub/mediakeysession.cpp [hunk 4]
```diff
@@ -154,9 +158,15 @@ void CMediaKeySession::Update(
   CDMI_DLOG() << "#mediakeysession.Run" << endl;
   std::string key_string(reinterpret_cast<const char*>(f_pbKeyMessageResponse),
                                    f_cbKeyMessageResponse);
+#if WPE
+  std::string key_id("1", 1);
+  media::KeyIdAndKeyPair key(key_id, key_string);
+  g_keys.assign(1, key);
+#else  //Chrome
```
Comment (petegriffin) [inline cdmi-stub/mediakeysession.cpp]: Can you explain why these changes are required?

If we really do have to have browser specific parts (which I'm not convinced we do) in the CDMi layer it needs to be decided on at run time (not via #ifdef). Maybe the browser agent string needs to be sent or similar.

File: rpc/opencdm_xdr_xdr.c [hunk 5]
```diff
@@ -49,7 +49,10 @@ bool_t
 xdr_rpc_request_create_session (XDR *xdrs, rpc_request_create_session *objp)
 {
 	register int32_t *buf;
-
+#if WPE
+        if (!xdr_int32_t (xdrs, &objp->license_type))
+                return FALSE;
+#endif
 	 if (!xdr_array (xdrs, (char **)&objp->init_data_type.init_data_type_val, (u_int *) &objp->init_data_type.init_data_type_len, ~0,
```
Comment (petegriffin) [inline rpc/opencdm_xdr_xdr.c]: General comment about all the commits, they need proper descriptions about why the change is being made. Also consider using git -rebase to squash any typos and fix earlier commits.

The end goal for this work should be to have a single cdmiservice binary which can work with both Chromium and WPE browsers.

Comment (psivasubramanian) [reply rpc/opencdm_xdr_xdr.c]: Ok, maybe the github GUI way I used is limiting me from fix/feature based commits (instead to file based) & rebasing. I will use git command-line then to have cleaner commits.

File: cdmi-stub/imp.h (hunk 1 above)
Comment (psivasubramanian) [reply cdmi-stub/imp.h]: To match the function call in cdmi/service.cpp, line 117.

File: rpc/opencdm_xdr.h (hunk 2 above)
Comment (psivasubramanian) [reply rpc/opencdm_xdr.h]: Maybe, I will restructure these changes so that WPE support coexist together with existing Chrome support. Currently browser support is based on compile type option - WPE/Chrome.

File: rpc/opencdm_xdr_svc.c (hunk 3 above)
Comment (psivasubramanian) [reply rpc/opencdm_xdr_svc.c]: Yes it can be, will review this.

File: cdmi-stub/mediakeysession.cpp (hunk 4 above)
Comment (psivasubramanian) [reply cdmi-stub/mediakeysession.cpp]: So far the URL we tested, does not sent the key in JSON format. That why there is no need to extract key from json.

**Comment by psivasubramanian** [comment]
Closing this pull request as the review changes requested here are available in https://github.com/linaro-home/open-content-decryption-module-cdmi/pull/8.
